//! Autogenerated weights for pallet_senate_upgrade
//!
//! THIS FILE WAS AUTO-GENERATED USING THE SUBSTRATE BENCHMARK CLI VERSION 4.0.0-dev
//! DATE: (date), STEPS: `50`, REPEAT: `20`, LOW RANGE: `[]`, HIGH RANGE: `[]`
//! WORST CASE MAP SIZE: `[1000000; 1000000]`
//! HOST: (host), CPU: (cpu)
//! EXECUTION: Some(Wasm), WASM-EXECUTION: Compiled, CHAIN: Some("dev"), DB CACHE: 1024

// Executed Command:
// ./target/production/substrate benchmark pallet
// --pallet=pallet_senate_upgrade
// --chain=dev
// --steps=50
// --repeat=20
// --extrinsic=*
// --wasm-execution=compiled
// --heap-pages=4096
// --output=./pallets/senate-upgrade/src/weights.rs
// --template=./.maintain/frame-weight-template.hbs

#![cfg_attr(rustfmt, rustfmt_skip)]
#![allow(unused_parens)]
#![allow(unused_imports)]
#![allow(missing_docs)]

use frame_support::{traits::Get, weights::Weight};
use core::marker::PhantomData;

/// Weight functions for `pallet_senate_upgrade`.
pub trait WeightInfo {
	fn senate_set_code() -> Weight;
	fn senate_dispatch_as_root() -> Weight;
}

/// Weights for pallet_senate_upgrade using the Substrate node and recommended hardware.
pub struct SubstrateWeight<T>(PhantomData<T>);
impl<T: frame_system::Config> WeightInfo for SubstrateWeight<T> {
	/// Storage: `System::BlockWeight` (r:1 w:0)
	/// Proof: `System::BlockWeight` (`max_values`: Some(1), `max_size`: Some(48), added: 543, mode: `MaxEncodedLen`)
	/// Storage: `System::Code` (r:0 w:1)
	/// Proof: `System::Code` (`max_values`: Some(1), `max_size`: None, mode: `Measured`)
	fn senate_set_code() -> Weight {
		// Proof Size summary in bytes:
		//  Measured:  `0`
		//  Estimated: `543`
		//  Minimum execution time: 100_000_000 nanoseconds.
		Weight::from_parts(100_000_000, 0)
			.saturating_add(Weight::from_parts(543, 0))
	}

	fn senate_dispatch_as_root() -> Weight {
		// Minimal overhead; the inner call weight is charged separately.
		Weight::from_parts(10_000_000, 0)
	}
}

